// Authentic Shega Generations mock data mirroring real Sanity schemas 1:1.

export const demoUpcomingEvent = {
  _id: "demo-event-1",
  title: "Regional CTF: Bahir Dar Circuit",
  type: "CTF",
  slug: { current: "bahir-dar-ctf" },
  eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
  location: "Bahir Dar, Amhara Region",
  coverImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800",
  registrationLink: "#",
};

export const demoEvents = [
  demoUpcomingEvent,
  {
    _id: "demo-event-2",
    title: "Simien Mountains Expedition",
    type: "Hiking",
    slug: { current: "simien-expedition" },
    eventDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    location: "Simien Mountains, Amhara Region",
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800",
    isUpcoming: false,
    registrationLink: "#",
  },
  {
    _id: "demo-event-3",
    title: "National Hackathon: Build for Home",
    type: "Hackathon",
    slug: { current: "build-for-home" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 55).toISOString(),
    location: "Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "#",
  },
];

export const demoCourses = [
  {
    _id: "demo-course-1",
    title: "Full-Stack Web & Mobile Architecture",
    instructor: "Zemichael Tefera • Lead Engineer",
    badgeCategory: "Tech Orientation",
    level: "Intermediate • 12 Weeks",
    snippet: "Master modern TypeScript, Next.js App Router, React Native, and PostgreSQL to craft resilient web and mobile platforms built for local commerce.",
    bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 1,
    rating: "4.9",
    enrolledCount: 140,
    tags: ["Next.js", "TypeScript", "React Native", "PostgreSQL"],
  },
  {
    _id: "demo-course-2",
    title: "Applied AI & Low-Resource Language Models",
    instructor: "Dr. Abera B. • AI Research Lead",
    badgeCategory: "Tech Orientation",
    level: "Advanced • 10 Weeks",
    snippet: "Train custom neural networks, fine-tune open-weights models (Llama 3, Mistral) on Amharic/Afan Oromo corpora, and build OCR pipelines for Ge'ez script.",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 2,
    rating: "5.0",
    enrolledCount: 95,
    tags: ["PyTorch", "HuggingFace", "Ge'ez OCR", "Llama 3"],
  },
  {
    _id: "demo-course-3",
    title: "DevOps, Containerization & Offline Edge Nodes",
    instructor: "Kidus Y. • Systems Architect",
    badgeCategory: "Tech Orientation",
    level: "Intermediate • 8 Weeks",
    snippet: "Construct GitOps CI/CD pipelines, Docker containers, and resilient Kubernetes clusters tailored for low-bandwidth, offline-first regional deployments.",
    bannerImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 3,
    rating: "4.8",
    enrolledCount: 110,
    tags: ["Docker", "Kubernetes", "GitOps", "Terraform"],
  },
  {
    _id: "demo-course-4",
    title: "Ethnomathematics & Tibeb Weaving Geometry",
    instructor: "Master Weaver Wolete & Shega Tech Team",
    badgeCategory: "Indigenous Knowledge",
    level: "All Levels • 6 Weeks",
    snippet: "Decode structural geometry patterns in traditional Ethiopian Tibeb textiles. Translate organic weaving matrices into responsive CSS grids and SVG graphic algorithms.",
    bannerImage: "https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 4,
    rating: "5.0",
    enrolledCount: 210,
    tags: ["Ethnomathematics", "SVG Grids", "Tibeb Geometry", "CSS Math"],
  },
  {
    _id: "demo-course-5",
    title: "Negotiation, Pitching & Venture Leadership",
    instructor: "Bethlehem T. & Shega Founders Network",
    badgeCategory: "Life Skills",
    level: "All Levels • 6 Weeks",
    snippet: "Master technical storytelling, contract negotiation, financial literacy, and community ethics. Prepare to pitch, launch, and sustain independent engineering ventures.",
    bannerImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 5,
    rating: "4.9",
    enrolledCount: 180,
    tags: ["Venture Pitching", "Financial Literacy", "Leadership", "Ethics"],
  },
  {
    _id: "demo-course-6",
    title: "Geospatial Data & Agricultural Logistics",
    instructor: "Tewodros A. • GIS Specialist",
    badgeCategory: "Tech Orientation",
    level: "Intermediate • 8 Weeks",
    snippet: "Build spatial data pipelines mapping regional supply chains, local crop micro-climates, and transport networks across Ethiopian secondary cities.",
    bannerImage: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "#",
    sequenceOrder: 6,
    rating: "4.9",
    enrolledCount: 85,
    tags: ["QGIS", "GeoJSON", "Python Data", "Logistics"],
  },
];

export const demoProjects = [
  {
    _id: "demo-project-1",
    title: "Adera Logistics Platform",
    creatorName: "Sara Mohammed",
    cohortLocation: "Hawassa Cohort",
    description: "Decentralized dispatch & inventory tracker for regional agricultural cooperatives. Connected 14 rural farming unions in Sidama, processing over $120k in regional grain trades.",
    impactMetric: "14 Unions Connected • $120k Processed",
    category: "Venture Startup",
    projectUrl: "#",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=800",
    quote: "Shega showed me how to turn local logistics challenges into production-grade software.",
    techStack: ["Next.js", "PostgreSQL", "Twilio SMS", "TailwindCSS"],
  },
  {
    _id: "demo-project-2",
    title: "Ge'ez Vision OCR",
    creatorName: "Dawit Kassaye",
    cohortLocation: "Bahir Dar Cohort",
    description: "Deep-learning optical character recognition model fine-tuned for historic Ge'ez and Amharic manuscripts. Digitized over 400 ancient texts for public archives.",
    impactMetric: "400+ Manuscripts Digitized • 98.4% Accuracy",
    category: "Open-Source AI",
    projectUrl: "#",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800",
    quote: "We combined our AI lab training with local manuscript preservation.",
    techStack: ["PyTorch", "OpenCV", "Tesseract", "FastAPI"],
  },
  {
    _id: "demo-project-3",
    title: "AgriSignal SMS",
    creatorName: "Hana Assefa",
    cohortLocation: "Adama Cohort",
    description: "USSD & SMS weather advisory delivering micro-climate frost alerts and market prices to smallholder farmers without smartphone or internet connectivity.",
    impactMetric: "12,500 Active Farmers • 4 Languages",
    category: "Offline Agritech",
    projectUrl: "#",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&q=80&w=800",
    quote: "Building offline-first tools meant our software actually reached local farm hands.",
    techStack: ["Node.js", "Africa's Talking API", "Redis", "USSD"],
  },
  {
    _id: "demo-project-4",
    title: "Tibeb Design System",
    creatorName: "Yonas & Samrawit",
    cohortLocation: "Mekelle Cohort",
    description: "An open-source generative CSS/SVG grid generator that converts traditional Ethiopian weaving math into production Web component design tokens.",
    impactMetric: "1,200+ GitHub Stars • Used in 15 Apps",
    category: "UI Framework",
    projectUrl: "#",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=800",
    quote: "Ethnomathematics became our superpower for creating authentic digital interfaces.",
    techStack: ["TypeScript", "SVG Engine", "Tailwind Plugin", "Web Components"],
  },
  {
    _id: "demo-project-5",
    title: "HealthReach Telemetry",
    creatorName: "Abdi Tolosa",
    cohortLocation: "Jima Cohort",
    description: "Low-bandwidth patient diagnostic sync tool operating over intermittent 2G networks, connecting remote rural health posts with referral hospitals.",
    impactMetric: "32 Clinics Deployed • 8,000 Patient Logs",
    category: "HealthTech",
    projectUrl: "#",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800",
    quote: "Our DevOps training helped us design software that never crashes when the network drops.",
    techStack: ["React Native", "SQLite", "Docker", "Go"],
  },
];

export const demoTestimonials = [
  {
    quote: "Shega gave me the space to write my first line of code. Today, I'm training low-resource NLP models translating educational textbooks into our regional languages.",
    author: "Tsion Kebede",
    role: "AI Researcher @ Lesan AI",
    track: "AI Laboratory Graduate",
    region: "Hawassa",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "The DevOps track wasn't theoretical — we managed live server nodes and deployment pipelines. Building real tools alongside regional peers taught me more than any online course.",
    author: "Yonas Alemu",
    role: "Lead Infrastructure Eng @ EthioCloud",
    track: "DevOps Pipeline Graduate",
    region: "Bahir Dar",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Ethnomathematics opened my eyes. Combining Tibeb weaving geometries with SVG grid algorithms gave me a distinct design language that set my work apart globally.",
    author: "Samrawit Birhan",
    role: "Senior Frontend Eng @ Gebeya",
    track: "Craft & Software Graduate",
    region: "Mekelle",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Our leadership cohort did more than teach programming syntax. We learned how to pitch investors, manage team dynamics, and build community solutions with genuine empathy.",
    author: "Abdi Tolosa",
    role: "Founder @ HealthReach Tech",
    track: "Software Studio Graduate",
    region: "Adama",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Shega's mentorship network didn't end at graduation. When we pitched our agritech logistics startup, our instructors were the first to review our technical pitch deck.",
    author: "Sara Mohammed",
    role: "Co-Founder & CEO @ Adera",
    track: "Venture Track Graduate",
    region: "Sidama",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Being anchored in our cultural heritage while mastering state-of-the-art AI gave us a unique perspective. We built Ge'ez OCR because nobody else was solving it for us.",
    author: "Dawit Kassaye",
    role: "Open-Source Lead @ Ge'ez AI",
    track: "AI Laboratory Graduate",
    region: "Gonder",
    year: "2024",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300",
  },
];

export const demoGallery = [
  {
    _id: "demo-g1",
    image: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=800",
    caption: "Diagnostic day, Addis cohort",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g2",
    image: "https://images.unsplash.com/photo-1486916856992-e4db22c8df33?auto=format&fit=crop&q=80&w=800",
    caption: "Simien ridge, sunrise briefing",
    categoryTag: "Expeditions",
  },
  {
    _id: "demo-g3",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=800",
    caption: "48-hour build, final hour",
    categoryTag: "Hackathons",
  },
  {
    _id: "demo-g4",
    image: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=800",
    caption: "Rebuilding a school lab",
    categoryTag: "Volunteer-Work",
  },
  {
    _id: "demo-g5",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800",
    caption: "First CTF flag, live",
    categoryTag: "Hackathons",
  },
  {
    _id: "demo-g6",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    caption: "Regional orientation, Bahir Dar",
    categoryTag: "Classroom",
  },
];

