// Authentic Shega Generation (ሸጋ ትውልድ) data mirroring real Sanity schemas 1:1.

export const demoUpcomingEvent = {
  _id: "demo-event-1",
  title: "Addis CTF: Root of the Rift",
  type: "CTF",
  slug: { current: "addis-ctf-root-of-the-rift" },
  eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
  location: "Addis Ababa Science Museum",
  coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800",
  isUpcoming: true,
  registrationLink: "/contact",
};

export const demoEvents = [
  demoUpcomingEvent,
  {
    _id: "demo-event-2",
    title: "Simien Highlands Learning Trek",
    type: "Hiking",
    slug: { current: "simien-highlands-learning-trek" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28).toISOString(),
    location: "Simien Mountains National Park",
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "/contact",
  },
  {
    _id: "demo-event-3",
    title: "Bahir Dar Hack for Good",
    type: "Hackathon",
    slug: { current: "bahir-dar-hack-for-good" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString(),
    location: "Bahir Dar University STEM Center",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "/contact",
  },
  {
    _id: "demo-event-4",
    title: "INSA & Ethiopian Artificial Intelligence Institute Excursion",
    type: "Tour",
    slug: { current: "insa-ai-institute-tour" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    location: "National AI Institute & INSA HQ, Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "/contact",
  },
  {
    _id: "demo-event-5",
    title: "Shega Summer Camp 2026 Tech Intake",
    type: "Tech Training",
    slug: { current: "shega-summer-camp-2026" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 75).toISOString(),
    location: "Tourism Training Institute (TTI), Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "/contact",
  },
  {
    _id: "demo-event-6",
    title: "'Sofor's Got Talent' & Gebeta Championship",
    type: "Charity",
    slug: { current: "sofors-got-talent-gebeta" },
    eventDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    location: "Guenet Hotel Mexico, Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800",
    isUpcoming: false,
    registrationLink: "/events",
  },
  {
    _id: "demo-event-7",
    title: "Managed Corporate AI & Digital Literacy Workshop",
    type: "Tech Training",
    slug: { current: "corporate-ai-workshop" },
    eventDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    location: "Tourism Training Institute (TTI), Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800",
    isUpcoming: false,
    registrationLink: "/events",
  },
];

export const demoCourses = [
  {
    _id: "demo-course-1",
    title: "Creative Kids: Block Coding & Logic (Ages 7–10)",
    instructor: "Shega Generation",
    badgeCategory: "Tech Orientation",
    level: "Beginner • 8 Weeks (Summer Camp)",
    snippet: "Learning through play, basic computer science concepts, Scratch block coding, Minecraft logic, cooking games, and tales of kindness.",
    bannerImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 1,
    rating: "5.0",
    enrolledCount: 200,
    tags: ["Scratch", "Minecraft", "Block Coding", "Tales of Kindness"],
  },
  {
    _id: "demo-course-2",
    title: "Astute Teens: Web Development & Heritage (Ages 11–13)",
    instructor: "Shega Generation & Sophor Code Academy",
    badgeCategory: "Tech Orientation",
    level: "Intermediate • 8 Weeks (Summer Camp)",
    snippet: "Logical reasoning, HTML/CSS web coding, life skills, and constructing real web portals showcasing Ethiopian tourism and heritage sites.",
    bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 2,
    rating: "4.9",
    enrolledCount: 180,
    tags: ["HTML5", "CSS3", "Tourism Web Portals", "Life Skills"],
  },
  {
    _id: "demo-course-3",
    title: "Leader Youth: Python, AI & Cybersecurity (Ages 14–18)",
    instructor: "Sophor Code Academy",
    badgeCategory: "Tech Orientation",
    level: "Advanced • 8 Weeks (Summer Camp)",
    snippet: "Advanced Python programming, web development, cybersecurity fundamentals, AI command engineering, entrepreneurship, and leadership.",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 3,
    rating: "5.0",
    enrolledCount: 150,
    tags: ["Python", "AI Engineering", "Cybersecurity", "Full-Stack"],
  },
  {
    _id: "demo-course-4",
    title: "Indigenous Knowledge, Ge'ez & History Secrets",
    instructor: "Shega Generation",
    badgeCategory: "Indigenous Knowledge",
    level: "All Ages • 8 Weeks",
    snippet: "Ancient Ge'ez fundamentals, Ethiopian history, engineering secrets behind historic landmarks, and traditional conflict resolution (Erq).",
    bannerImage: "https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 4,
    rating: "5.0",
    enrolledCount: 200,
    tags: ["Ge'ez", "Ethiopian History", "Landmark Engineering", "Erq"],
  },
  {
    _id: "demo-course-5",
    title: "Etiquette, Hospitality & Life Skills (የማዕድ ስነ-ስርዓት)",
    instructor: "Shega Generation & TTI Hospitality",
    badgeCategory: "Life Skills",
    level: "All Ages • 8 Weeks",
    snippet: "Practical instruction in የማዕድ ስነ-ስርዓት (Dining Etiquette), ፈገግታና አዎንታዊ ተግባቦት (Positive Communication) through interactive games, mineralogy, and public speaking.",
    bannerImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 5,
    rating: "4.9",
    enrolledCount: 190,
    tags: ["የማዕድ ስነ-ስርዓት", "Dining Etiquette", "Communication", "Life Skills"],
  },
  {
    _id: "demo-course-6",
    title: "Real-World Student Development Lab",
    instructor: "Shega Generation",
    badgeCategory: "Tech Orientation",
    level: "Senior Level • Year-Round",
    snippet: "Senior students execute external software development contracts for businesses—gaining portfolio experience while earning money for their contributions.",
    bannerImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 6,
    rating: "5.0",
    enrolledCount: 45,
    tags: ["Commercial Contracts", "Client Builds", "Earn While Learning", "Software Lab"],
  },
];

export const demoProjects = [
  {
    _id: "demo-project-1",
    title: "National Radio Feature: Youth Tech & AI Innovation",
    creatorName: "Astute Teens & Leader Youth Cohort",
    cohortLocation: "Fana FM 98.1 • National Broadcast",
    mediaOutlet: "Fana FM 98.1 Radio",
    description: "Special radio broadcast featuring Shega Generation students discussing how 11-18 year olds master Python, AI command engineering, and indigenous Ethiopian math during summer camp.",
    impactMetric: "Fana FM Radio Feature • 100K+ Listeners",
    category: "Radio Programs",
    projectUrl: "https://www.youtube.com/watch?v=d_k8kS0wJvg",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800",
    quote: "Speaking on national radio gave our young coders a platform to inspire youth across Ethiopia.",
    techStack: ["Radio Broadcast", "Python AI", "Youth Leadership", "Fana FM"],
  },
  {
    _id: "demo-project-2",
    title: "Ethiopian Youth Tech Podcast Interview",
    creatorName: "Leader Youth AI Team",
    cohortLocation: "Shega Tech Podcast Studio",
    mediaOutlet: "Tech & Culture Podcast",
    description: "In-depth podcast episode with student developers demonstrating custom AI command engineering models and OCR translation for ancient Ge'ez manuscripts.",
    impactMetric: "Tech Podcast Episode • Ge'ez AI OCR",
    category: "Podcasts",
    projectUrl: "https://www.youtube.com/watch?v=L_LUpnjgPso",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&q=80&w=800",
    quote: "Our students explained how ancient Ge'ez preservation and modern neural networks work together.",
    techStack: ["Podcast", "PyTorch", "Ge'ez Script", "AI Prompting"],
  },
  {
    _id: "demo-project-3",
    title: "Facebook Live Showcase: Creative Kids Scratch & Gebeta",
    creatorName: "Creative Kids Cohort (Ages 7–10)",
    cohortLocation: "TTI Hub, Addis Ababa",
    mediaOutlet: "Shega Facebook Broadcast",
    description: "Viral Facebook video showcase documenting 7-to-10-year-old children building interactive block games, Minecraft logic structures, and digital Gebeta matrix engines.",
    impactMetric: "Facebook Live Video • 25K Views",
    category: "Interviews",
    projectUrl: "https://www.facebook.com/shegagenerations",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=800",
    quote: "Parents and educators across Facebook watched 8-year-olds solve complex algorithmic logic.",
    techStack: ["Facebook Live", "Scratch Logic", "Gebeta Math", "Block Coding"],
  },
  {
    _id: "demo-project-4",
    title: "Commercial Client Software Lab Contracts",
    creatorName: "Senior Student Developers",
    cohortLocation: "Shega Development Lab",
    mediaOutlet: "Client Software Contracts",
    description: "Senior students executing commercial software contracts for external businesses. Developers earn early financial income while building production web & mobile systems.",
    impactMetric: "8 Commercial Contracts • Paid Lab",
    category: "Programs",
    projectUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    quote: "Our student developers earn early financial independence while delivering quality software to client businesses.",
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "PostgreSQL"],
  },
];

export const demoTestimonials = [
  {
    quote: "Shega Generation was founded to shape a well-rounded Ethiopian youth demographic—combining cutting-edge software engineering and AI with deep cultural respect and character.",
    author: "Samuel Geremew",
    role: "Founder @ Shega Generation",
    track: "Leadership & Vision",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Our two-month summer camp hosts up to 200 students per batch. From Scratch block coding for 7-year-olds to Python, web dev, and AI for teens, every child has a structured pathway.",
    author: "Zemichael Tefera",
    role: "Chief Coordinator & Senior Instructor",
    track: "Summer Camp Operations & Web Architecture",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "In Leader Youth (Ages 14–18), we dive into Python, web development, cybersecurity, and AI command engineering. Our students build real commercial software systems.",
    author: "Thomas Hailu",
    role: "Core Instructor & Mentor",
    track: "Leader Youth & Advanced Tech",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Teaching የማዕድ ስነ-ስርዓት (Dining Etiquette), positive communication (ፈገግታና አዎንታዊ ተግባቦት), and self-defense ensures our students grow into respectful, well-rounded leaders.",
    author: "Gebriel Kassahun",
    role: "Core Instructor & Life Skills Lead",
    track: "Hospitality & Life Skills",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Anchoring our youth in ancient Ge'ez fundamentals, Ethiopian history, and traditional conflict resolution (Erq) gives them deep pride in who they are as they master technology.",
    author: "Hizkeal",
    role: "Core Instructor & Mentor",
    track: "Indigenous Knowledge & Ge'ez",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300",
  },
];

export const demoGallery = [
  {
    _id: "demo-g1",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    caption: "Field trip to INSA & Ethiopian Artificial Intelligence Institute",
    categoryTag: "Expeditions",
  },
  {
    _id: "demo-g2",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
    caption: "Creative Kids (Ages 7–10) Scratch block coding session",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g3",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    caption: "Astute Teens (Ages 11–13) constructing Ethiopian tourism web portals",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g4",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    caption: "Leader Youth (Ages 14–18) AI command engineering & Python lab",
    categoryTag: "Hackathons",
  },
  {
    _id: "demo-g5",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800",
    caption: "Hands-on የማዕድ ስነ-ስርዓት (Dining Etiquette) session at TTI",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g6",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800",
    caption: "'Sofor's Got Talent' & Gebeta Championship at Guenet Hotel Mexico",
    categoryTag: "Volunteer-Work",
  },
];

export const demoPartners = [
  {
    _id: "demo-partner-1",
    name: "Sofor Code Academy",
    role: "Advanced Coding & Robotics Partner",
    description: "Direct partner executing advanced programming languages, Python labs, AI command engineering, and robotics curriculum.",
    websiteUrl: "https://shegagenerations.org/contact",
    order: 1,
  },
  {
    _id: "demo-partner-2",
    name: "Tourism Training Institute (TTI)",
    role: "Facility & Hospitality Partner",
    description: "Facility partner providing state-of-the-art computer labs, green grounds, and practical hospitality environments.",
    websiteUrl: "https://shegagenerations.org/contact",
    order: 2,
  },
  {
    _id: "demo-partner-3",
    name: "Guenet Hotel Mexico",
    role: "Hospitality & Venue Partner",
    description: "Hospitality and official event venue partner hosting summer workshops, student showcases, and cultural gatherings.",
    websiteUrl: "https://shegagenerations.org/contact",
    order: 3,
  },
  {
    _id: "demo-partner-4",
    name: "Samilos Media & Communications",
    role: "Media & Production Partner",
    description: "Media production partner documenting student progress, producing documentaries, and broadcasting national cohort stories.",
    websiteUrl: "https://shegagenerations.org/contact",
    order: 4,
  },
  {
    _id: "demo-partner-5",
    name: "Enqu Events",
    role: "Event Production & Logistics Partner",
    description: "Event organizing partner coordinating national youth talent showcases, robotics competitions, and community drives.",
    websiteUrl: "https://shegagenerations.org/contact",
    order: 5,
  },
];

export const demoTeamMembers = [
  // 1. Board of Directors / Council Governance
  {
    _id: "demo-team-sahret",
    name: "Sahret Sefa (ወ/ሮ ሳህረት ሰፋ)",
    role: "Board Council President",
    department: "board",
    responsibilities: "Provides strategic vision, high-level governance, and institutional oversight for the organization.",
    bio: "Provides strategic vision, high-level governance, and institutional oversight for Shega Generation across all organizational initiatives.",
    quote: "Guiding the strategic vision and institutional governance to build sustainable impact for Ethiopian youth.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Board Council President", "Institutional Governance"],
    socialLinks: { email: "sahret@shegagenerations.org" },
    order: 1,
  },
  {
    _id: "demo-team-selamawit-prof",
    name: "Prof. Selamawit Mekonnen (ፕሮፌሰር ሰላማዊት መኮንን)",
    role: "Board Secretary",
    department: "board",
    responsibilities: "Manages board communications, governance documentation, and official policy compliance.",
    bio: "Manages board communications, governance documentation, and official policy compliance for Shega Generation.",
    quote: "Ensuring rigorous documentation, transparent governance, and institutional policy compliance.",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Board Secretary", "Policy Compliance Lead"],
    socialLinks: { email: "selamawit.m@shegagenerations.org" },
    order: 2,
  },
  {
    _id: "demo-team-henok",
    name: "Dr. Henok Mulugeta (ዶክተር ሄኖክ ሙሉጌታ)",
    role: "Board Member",
    department: "board",
    responsibilities: "Provides advisory support, strategic direction, and institutional oversight across organizational initiatives.",
    bio: "Dr. Henock Mulugeta is an experienced academician and researcher, currently serving as an Associate Professor of Electrical and Computer Engineering and Head of the School of Information Technology and Engineering (SiTE) at AAU. He holds a PhD in Computer Engineering from AAU's SECE. Throughout his 20-year career, he has authored over 22 research articles in networking, cybersecurity, AI, and Cyber-intelligence. Dr. Henock actively collaborates with IGAD's Security Sector Program providing cybersecurity and AI trainings across Ethiopia, Uganda, and Kenya, and serves as a consultant for institutions including the Ethiopian Artificial Intelligence Institute (EAII).",
    quote: "Promoting institutional excellence, cybersecurity research, and AI innovation for Ethiopian youth and regional stability.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Board Member", "Head of SiTE (AAU)", "PhD Computer Engineering", "EAII Consultant", "Cybersecurity & AI Researcher"],
    socialLinks: { email: "henok@shegagenerations.org" },
    order: 3,
  },
  {
    _id: "demo-team-tibebu",
    name: "Tibebu Belete (ጥበቡ በለጠ)",
    role: "Board Member",
    department: "board",
    isBoardMember: true,
    isExecutiveLeader: false,
    isTeacher: false,
    responsibilities: "Provides advisory support, strategic direction, and institutional oversight across organizational initiatives.",
    bio: "Provides advisory support, strategic direction, and institutional oversight across organizational initiatives.",
    quote: "Supporting organizational growth and institutional development across Ethiopia.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Board Member", "Institutional Support"],
    socialLinks: { email: "tibebu@shegagenerations.org" },
    order: 4,
  },

  // 2. Executive & Operational Leadership
  {
    _id: "demo-team-samuel",
    name: "Samuel Geremew (ሳሙኤል ገረመው)",
    role: "Founder, Executive Director & Board Member",
    department: "executive",
    isBoardMember: true,
    isExecutiveLeader: true,
    isTeacher: true,
    teachingSubject: "Computer Science & Cybersecurity Fundamentals",
    teachingPeriod: "2021 – Present",
    responsibilities: "Drives the core vision, strategic partnerships, and overall operations of Shega Generation.",
    bio: "Samuel Geremew is a computer science researcher, cybersecurity specialist, educator, and media entrepreneur with expertise in digital security, technology education, and youth development. Holding a Master's degree in Computer Science with a specialization in Cybersecurity, he serves as a higher education lecturer and researcher. Samuel is the Founder and Executive Director of Shega Generation (የሸጋ ትውልድ), General Manager of Samelos Media & Communication, and host of the popular 'Shaga Chewata' (የሸጋ ጨዋታ) radio and TV program. He also serves as an Honorary Ambassador for Mary Joy Ethiopia.",
    quote: "Share our knowledge in kindness. When you empower a child with technology and character, you transform an entire generation.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: [
      "Founder & Executive Director",
      "MSc Computer Science (Cybersecurity)",
      "Higher Ed Lecturer & Researcher",
      "Host 'Shaga Chewata' Radio & TV",
      "MaryJoy Ethiopia Ambassador",
      "GM Samelos Media",
    ],
    socialLinks: {
      tiktok: "https://www.tiktok.com/@samuelgeremew_21",
      facebook: "https://web.facebook.com/share/g/18foDKzcBS/",
      email: "samuel@shegagenerations.org",
    },
    order: 5,
  },
  {
    _id: "demo-team-zemichael",
    name: "Zemichael Tefera (አቶ ዘሚካኤል ተፈራ)",
    role: "Board Member & Talent Head (Chief Coordinator)",
    department: "executive",
    isBoardMember: true,
    isExecutiveLeader: true,
    isTeacher: true,
    teachingSubject: "Full-Stack Web Dev & Technical Mentorship",
    teachingPeriod: "2021 – Present",
    responsibilities: "Oversees talent development, student mentorship frameworks, cohort placements, and technical instruction.",
    bio: "Chief Coordinator overseeing talent development, student mentorship frameworks, cohort placements, and technical instruction across summer camps and software labs.",
    quote: "Empowering every student with high-level technical mastery and individual mentorship.",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: [
      "Board Member",
      "Talent Head",
      "Chief Coordinator",
      "Senior Technical Lead",
    ],
    socialLinks: {
      email: "zemichael@shegagenerations.org",
    },
    order: 6,
  },
  {
    _id: "demo-team-tedros",
    name: "Tedros Molla (አቶ ቴድሮስ ሞላ)",
    role: "Public Relations (PR)",
    department: "executive",
    isBoardMember: false,
    isExecutiveLeader: true,
    isTeacher: false,
    responsibilities: "Manages media relations, public engagement, and organizational communications.",
    bio: "Manages media relations, public engagement, press releases, and organizational communications across national channels.",
    quote: "Amplifying the stories and achievements of Ethiopian youth coders across national media.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Public Relations Lead", "Media Relations"],
    socialLinks: {
      email: "tedros@shegagenerations.org",
    },
    order: 7,
  },
  {
    _id: "demo-team-thomas",
    name: "Thomas Hailu (አቶ ቶማስ ሃይሉ)",
    role: "Training Coordinator",
    department: "executive",
    isBoardMember: false,
    isExecutiveLeader: true,
    isTeacher: true,
    teachingSubject: "Training Logistics & Practical Coding Execution",
    teachingPeriod: "2023 – Present",
    responsibilities: "Directs day-to-day training logistics, curriculum execution, and instructor management across cohorts.",
    bio: "Directs day-to-day training logistics, curriculum execution, class schedules, and instructor management across all cohorts.",
    quote: "Delivering seamless daily instruction and curriculum execution for every cohort.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Training Coordinator", "Curriculum Logistics Lead"],
    socialLinks: {
      email: "thomas@shegagenerations.org",
    },
    order: 8,
  },

  // 3. Technical, Cultural & Student Mentors
  {
    _id: "demo-team-dawit",
    name: "Dawit Kassaye (ዳዊት ካሳዬ)",
    role: "Senior AI & Full-Stack Mentor",
    department: "tech",
    isBoardMember: false,
    isExecutiveLeader: false,
    isTeacher: true,
    teachingSubject: "Python Programming & AI Command Engineering",
    teachingPeriod: "2022 – Present",
    responsibilities: "Leads Leader Youth (Ages 14-18) tracks and manages Commercial Student Software Lab.",
    bio: "Senior software engineer specializing in Next.js, Python, and AI prompt engineering.",
    quote: "Our students don't just write code—they build commercial software that businesses rely on.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Full-Stack Engineer", "Commercial Lab Lead"],
    socialLinks: { email: "dawit@shegagenerations.org" },
    order: 9,
  },
  {
    _id: "demo-team-bethlehem",
    name: "Bethlehem Tadesse (ቤተልሔም ታደሰ)",
    role: "Director of Hospitality & Character Etiquette",
    department: "cultural",
    responsibilities: "Leads የማዕድ ስነ-ስርዓት (Dining Etiquette) & positive communication modules with TTI.",
    bio: "Tourism Training Institute partner liaison leading character etiquette instruction.",
    quote: "Etiquette and warmth are the bedrock of Ethiopian culture.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["TTI Hospitality Consultant", "Character Advisor"],
    socialLinks: { email: "bethlehem@shegagenerations.org" },
    order: 10,
  },
  {
    _id: "demo-team-yonas",
    name: "Yonas Bekele (ዮናስ በቀለ)",
    role: "Robotics & Hardware Lab Instructor",
    department: "tech",
    responsibilities: "Directs robotics, Arduino, and interactive electronics modules.",
    bio: "Sofor Code Academy robotics lead specializing in hardware engineering.",
    quote: "Watching kids wire their first autonomous robot is priceless.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Sofor Code Academy Partner", "Robotics Lead"],
    socialLinks: { email: "yonas@shegagenerations.org" },
    order: 11,
  },
  {
    _id: "demo-team-kaleb",
    name: "Kaleb Tesfaye (ካሌብ ተስፋዬ)",
    role: "Senior Peer Mentor & Student Council Lead",
    department: "student-mentors",
    responsibilities: "Coordinates student council activities and junior cohort mentorship.",
    bio: "Original 2021 student cohort member now serving as student council lead.",
    quote: "I started on a wooden stool at Weyn Coffee. Now I mentor 60+ younger kids every summer.",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600",
    organizationAffiliations: ["Alumni Class of 2021", "Student Council Lead"],
    socialLinks: { email: "kaleb@shegagenerations.org" },
    order: 12,
  },
];

export const demoStoryMilestones = [
  {
    _id: "demo-story-1",
    stepNumber: 1,
    year: "2021",
    title: "The Coffee House Genesis (Weyn Coffee)",
    location: "Weyn Coffee House, Addis Ababa",
    description: "Founder Samuel Geremew—higher education university lecturer, Ambassador for MaryJoy NGO, and CEO of Samilos Media—launched Shega Generation under the motto 'Share our knowledge in kindness.' Gathering a few bright children from different neighborhoods, he began teaching university-level computer science concepts inside his sister Weyn's traditional coffee house on small wooden stools on Sunday mornings.",
    quote: "We started on small wooden stools in my sister Weyn's coffee shop. We had no fancy labs, but we had unlimited curiosity and a spirit of kindness.",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "Sister Weyn's Traditional Coffee House",
      "Sunday Morning Sessions",
      "University-Level Concepts for Kids",
      "Small Wooden Stools",
    ],
  },
  {
    _id: "demo-story-2",
    stepNumber: 2,
    year: "2022",
    title: "Peer Mentorship & Organic Expansion",
    location: "Weyn Coffee House, Addis Ababa",
    description: "Word spread quickly across the community. The young kids caught on so fast that early cohort members naturally transformed into mentors for new joiners. Sunday morning sessions expanded to full capacity as students began building basic web pages and solving mathematical logic puzzles.",
    quote: "The magic happened when 10-year-olds who learned Scratch and Ge'ez counting the year before started teaching the new 7-year-olds.",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "Peer-to-Peer Mentorship Model",
      "Expanding Sunday Cohorts",
      "Logic & Web Fundamentals",
    ],
  },
  {
    _id: "demo-story-3",
    stepNumber: 3,
    year: "2023",
    title: "1st Summer Camp at Guenet Hotel",
    location: "Guenet Hotel Mexico, Addis Ababa",
    description: "Due to personal circumstances, Weyn Coffee House was forced to close. Refusing to let the movement end, Samuel initiated strategic discussions with the Tourism Training Institute (TTI). Gracious leadership at TTI offered venue space at Guenet Hotel, launching the historic 1st Shega Generation Summer Camp.",
    quote: "When the coffee house closed, I refused to let our kids' dreams stop. TTI stepped up and opened the doors of Guenet Hotel.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "1st Official Summer Camp",
      "Strategic TTI Partnership",
      "Guenet Hotel Venue",
      "Overcoming Adversity",
    ],
  },
  {
    _id: "demo-story-4",
    stepNumber: 4,
    year: "2024",
    title: "2nd Summer Camp (Guenet Hotel & TTI Campus)",
    location: "TTI Main Campus & Guenet Hotel",
    description: "The 2nd Summer Camp scaled significantly across both Guenet Hotel and the main TTI institute campus. TTI leadership and staff enrolled their own children into Shega Generation, forging a deep institutional bond and adding structured hospitality etiquette into the curriculum.",
    quote: "When staff at TTI enrolled their own children into our classes, we knew we were building something truly special.",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "2nd Summer Camp",
      "Dual Campus Expansion",
      "TTI Staff Children Enrolled",
      "Hospitality Etiquette Introduced",
    ],
  },
  {
    _id: "demo-story-5",
    stepNumber: 5,
    year: "2025",
    title: "3rd Summer Camp at TTI (Computer Labs Unlocked)",
    location: "TTI Computer Laboratories",
    description: "TTI officially unlocked state-of-the-art computer laboratories for Shega Generation students. Kids practiced Python programming, AI command engineering, and full-stack web development hands-on on high-performance desktop workstations.",
    quote: "Moving from wooden stools to full-fledged computer laboratories gave our students the exact tools needed to build real-world software.",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "3rd Summer Camp",
      "Dedicated TTI Computer Labs",
      "Hands-on Python & AI Engineering",
      "TTI Institutional Commitment",
    ],
  },
  {
    _id: "demo-story-6",
    stepNumber: 6,
    year: "2026",
    title: "Smart Classrooms & Commercial Student Software Lab",
    location: "TTI Smart Classrooms & National Media Outlets",
    description: "Today, Shega Generation operates active cohorts inside TTI smart classrooms and computer labs. Senior students run a Commercial Software Lab executing paid client software builds, while national broadcasts on Fana FM and Samilos Media showcase youth innovations.",
    quote: "Our students aren't just learning—they are executing commercial client contracts and broadcasting their projects nationally.",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "Active TTI Smart Classrooms",
      "Commercial Student Software Lab",
      "National Radio & TV Broadcasts",
      "500+ Alumni Network",
    ],
  },
  {
    _id: "demo-story-7",
    stepNumber: 7,
    year: "The Horizon",
    title: "The Shega Innovation Campus & Nationwide Reach",
    location: "Permanent 24/7 Innovation Campus, Ethiopia",
    description: "The ultimate vision: Building a dedicated, permanent 24/7 Shega Innovation Campus in Addis Ababa—equipped with overnight coding labs, startup incubation facilities, rest spaces, hardware workshops, and multi-tier cohort capacity reachable from every corner of Ethiopia.",
    quote: "A safe, fear-free sanctuary where Ethiopia's brightest minds can practice overnight, build startups, and solve real-world problems.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
    highlights: [
      "24/7 Dedicated Innovation Campus",
      "Overnight Practice Labs & Rest Facilities",
      "Startup Incubation Center",
      "Nationwide Regional Cohorts",
    ],
  },
];

