// Authentic Shega Generation (ሸጋ ትውልድ) data mirroring real Sanity schemas 1:1.

export const demoUpcomingEvent = {
  _id: "demo-event-1",
  title: "Shega Summer Camp 2026 Batch Intake & Assessment",
  type: "Tech Training",
  slug: { current: "shega-summer-camp-2026" },
  eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
  location: "Tourism Training Institute (TTI) & Guenet Hotel Mexico, Addis Ababa",
  coverImage: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
  isUpcoming: true,
  registrationLink: "/contact",
};

export const demoEvents = [
  demoUpcomingEvent,
  {
    _id: "demo-event-2",
    title: "INSA & Ethiopian Artificial Intelligence Institute Excursion",
    type: "Tour",
    slug: { current: "insa-ai-institute-tour" },
    eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35).toISOString(),
    location: "National AI Institute & INSA Headquarters, Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=800",
    isUpcoming: true,
    registrationLink: "/contact",
  },
  {
    _id: "demo-event-3",
    title: "'Sofor's Got Talent' & Gebeta Cultural Championship",
    type: "Charity",
    slug: { current: "sofors-got-talent-gebeta" },
    eventDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    location: "Guenet Hotel Mexico, Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800",
    isUpcoming: false,
    registrationLink: "/events",
  },
  {
    _id: "demo-event-4",
    title: "Managed Corporate AI & Digital Literacy Workshop",
    type: "Tech Training",
    slug: { current: "corporate-ai-workshop" },
    eventDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    location: "Tourism Training Institute (TTI), Addis Ababa",
    coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800",
    isUpcoming: false,
    registrationLink: "/events",
  },
];

export const demoCourses = [
  {
    _id: "demo-course-1",
    title: "Creative Kids: Block Coding & Logic (Ages 7–10)",
    instructor: "Samuel Geremew & Sofor Code Academy",
    badgeCategory: "Tech Orientation",
    level: "Beginner • 8 Weeks (Summer Camp)",
    snippet: "Learning through play, basic computer science concepts, Scratch block coding, Minecraft logic, cooking games, and tales of kindness.",
    bannerImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 1,
    rating: "5.0",
    enrolledCount: 200,
    tags: ["Scratch", "Minecraft", "Block Coding", "Tales of Kindness"],
  },
  {
    _id: "demo-course-2",
    title: "Astute Teens: Web Development & Heritage (Ages 11–13)",
    instructor: "Zemichael Tefera • Chief Coordinator",
    badgeCategory: "Tech Orientation",
    level: "Intermediate • 8 Weeks (Summer Camp)",
    snippet: "Logical reasoning, HTML/CSS web coding, life skills, and constructing real web portals showcasing Ethiopian tourism and heritage sites.",
    bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 2,
    rating: "4.9",
    enrolledCount: 180,
    tags: ["HTML5", "CSS3", "Tourism Web Portals", "Life Skills"],
  },
  {
    _id: "demo-course-3",
    title: "Leader Youth: Python, AI & Cybersecurity (Ages 14–18)",
    instructor: "Thomas Hailu • Lead Technical Instructor",
    badgeCategory: "Tech Orientation",
    level: "Advanced • 8 Weeks (Summer Camp)",
    snippet: "Advanced Python programming, web development, cybersecurity fundamentals, AI command engineering, entrepreneurship, and leadership.",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 3,
    rating: "5.0",
    enrolledCount: 150,
    tags: ["Python", "AI Engineering", "Cybersecurity", "Full-Stack"],
  },
  {
    _id: "demo-course-4",
    title: "Indigenous Knowledge, Ge'ez & History Secrets",
    instructor: "Hizkeal • Core Instructor & Mentor",
    badgeCategory: "Indigenous Knowledge",
    level: "All Ages • 8 Weeks",
    snippet: "Ancient Ge'ez fundamentals, Ethiopian history, engineering secrets behind historic landmarks, and traditional conflict resolution (Erq).",
    bannerImage: "https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 4,
    rating: "5.0",
    enrolledCount: 200,
    tags: ["Ge'ez", "Ethiopian History", "Landmark Engineering", "Erq"],
  },
  {
    _id: "demo-course-5",
    title: "Etiquette, Hospitality & Life Skills (የማዕድ ስነ-ስርዓት)",
    instructor: "Gebriel Kassahun & TTI Hospitality Team",
    badgeCategory: "Life Skills",
    level: "All Ages • 8 Weeks",
    snippet: "Practical instruction in የማዕድ ስነ-ስርዓት (Dining Etiquette), ፈገግታና አዎንታዊ ተግባቦት (Positive Communication) through interactive games, mineralogy, and public speaking.",
    bannerImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 5,
    rating: "4.9",
    enrolledCount: 190,
    tags: ["የማዕድ ስነ-ስርዓት", "Dining Etiquette", "Communication", "Life Skills"],
  },
  {
    _id: "demo-course-6",
    title: "Real-World Student Development Lab",
    instructor: "Samuel Geremew & Zemichael Tefera",
    badgeCategory: "Tech Orientation",
    level: "Senior Level • Year-Round",
    snippet: "Senior students execute external software development contracts for businesses—gaining portfolio experience while earning money for their contributions.",
    bannerImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    externalLmsUrl: "/contact",
    sequenceOrder: 6,
    rating: "5.0",
    enrolledCount: 45,
    tags: ["Commercial Contracts", "Client Builds", "Earn While Learning", "Software Lab"],
  },
];

export const demoProjects = [
  {
    _id: "demo-project-1",
    title: "Ethiopian Tourism Heritage Portal",
    creatorName: "Astute Teens Cohort (Led by Zemichael Tefera)",
    cohortLocation: "Addis Ababa Cohort",
    description: "Interactive web portal showcasing historic Ethiopian landmarks and cultural sites, built by 11-13 year old students during the Shega Summer Camp.",
    impactMetric: "25 Landmarks Featured • Built by Teens",
    category: "Student Project",
    projectUrl: "https://shegagenerations.org",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=800",
    quote: "Building real tourism portals gave our 12-year-old students confidence to present their work to national partners.",
    techStack: ["HTML5", "CSS3", "JavaScript", "Tourism Data"],
  },
  {
    _id: "demo-project-2",
    title: "Ge'ez AI Command & OCR Engine",
    creatorName: "Leader Youth AI Team (Led by Thomas Hailu & Samuel Geremew)",
    cohortLocation: "Addis Ababa Cohort",
    description: "Custom AI command engineering and optical character recognition model tailored for ancient Ge'ez manuscripts and Ethiopian linguistic datasets.",
    impactMetric: "AI Command Model • Ge'ez Script OCR",
    category: "Open-Source AI",
    projectUrl: "https://shegagenerations.org",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800",
    quote: "Our youth combined AI prompt engineering with Ethiopian indigenous script preservation.",
    techStack: ["Python", "PyTorch", "Ge'ez OCR", "AI Command"],
  },
  {
    _id: "demo-project-3",
    title: "Shega Student Lab Commercial Builds",
    creatorName: "Senior Student Developers",
    cohortLocation: "Shega Development Lab",
    description: "External software development contracts managed by Shega Generation for external businesses. Senior students execute commercial builds and earn money for their work.",
    impactMetric: "8 External Contracts • Student Paid Lab",
    category: "Venture Startup",
    projectUrl: "https://shegagenerations.org",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
    quote: "Our student developers earn early financial independence while delivering quality software to client businesses.",
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "PostgreSQL"],
  },
  {
    _id: "demo-project-4",
    title: "Gebeta & Ethnomathematics Digital Engine",
    creatorName: "Creative Kids & Youth Coders (Led by Hizkeal & Gebriel Kassahun)",
    cohortLocation: "TTI Hub, Addis Ababa",
    description: "Digital Ethiopian board game and matrix UI grid generator converting traditional Gebeta game rules and Tibeb patterns into interactive web code.",
    impactMetric: "Traditional Gebeta • Tibeb SVG Math",
    category: "UI Framework",
    projectUrl: "https://shegagenerations.org",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=800",
    quote: "Gebeta and Tibeb patterns taught us that Ethiopian indigenous games contain deep computational mathematics.",
    techStack: ["TypeScript", "SVG Engine", "Gebeta Math", "CSS Grids"],
  },
];

export const demoTestimonials = [
  {
    quote: "Shega Generation was founded to shape a well-rounded Ethiopian youth demographic—combining cutting-edge software engineering and AI with deep cultural respect and character.",
    author: "Samuel Geremew",
    role: "Founder @ Shega Generation",
    track: "Leadership & Vision",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Our two-month summer camp hosts up to 200 students per batch. From Scratch block coding for 7-year-olds to Python, web dev, and AI for teens, every child has a structured pathway.",
    author: "Zemichael Tefera",
    role: "Chief Coordinator & Senior Instructor",
    track: "Summer Camp Operations & Web Architecture",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "In Leader Youth (Ages 14–18), we dive into Python, web development, cybersecurity, and AI command engineering. Our students build real commercial software systems.",
    author: "Thomas Hailu",
    role: "Core Instructor & Mentor",
    track: "Leader Youth & Advanced Tech",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Teaching የማዕድ ስነ-ስርዓት (Dining Etiquette), positive communication (ፈገግታና አዎንታዊ ተግባቦት), and self-defense ensures our students grow into respectful, well-rounded leaders.",
    author: "Gebriel Kassahun",
    role: "Core Instructor & Life Skills Lead",
    track: "Hospitality & Life Skills",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300",
  },
  {
    quote: "Anchoring our youth in ancient Ge'ez fundamentals, Ethiopian history, and traditional conflict resolution (Erq) gives them deep pride in who they are as they master technology.",
    author: "Hizkeal",
    role: "Core Instructor & Mentor",
    track: "Indigenous Knowledge & Ge'ez",
    location: "Addis Ababa",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300",
  },
];

export const demoGallery = [
  {
    _id: "demo-g1",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    caption: "Field trip to INSA & Ethiopian Artificial Intelligence Institute",
    categoryTag: "Expeditions",
  },
  {
    _id: "demo-g2",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
    caption: "Creative Kids (Ages 7–10) Scratch block coding session",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g3",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    caption: "Astute Teens (Ages 11–13) constructing Ethiopian tourism web portals",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g4",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    caption: "Leader Youth (Ages 14–18) AI command engineering & Python lab",
    categoryTag: "Hackathons",
  },
  {
    _id: "demo-g5",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800",
    caption: "Hands-on የማዕድ ስነ-ስርዓት (Dining Etiquette) session at TTI",
    categoryTag: "Classroom",
  },
  {
    _id: "demo-g6",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800",
    caption: "'Sofor's Got Talent' & Gebeta Championship at Guenet Hotel Mexico",
    categoryTag: "Volunteer-Work",
  },
];
