import { defineArrayMember, defineField, defineType } from "sanity";
import { CogIcon } from "@sanity/icons";

export default defineType({
  name: "siteSettings",
  title: "Site Settings & Page Copy",
  type: "document",
  icon: CogIcon,
  groups: [
    { name: "about", title: "About Us Page", default: true },
    { name: "hero", title: "Home Hero Section" },
    { name: "statement", title: "Statement Banner" },
    { name: "cultural", title: "Cultural Anchoring" },
    { name: "pedagogical", title: "Pedagogical Section" },
    { name: "curriculum", title: "Curriculum Section" },
    { name: "journeys", title: "Journeys Section" },
    { name: "testimonials", title: "Testimonials Section" },
    { name: "events", title: "Events Page & Gatherings" },
    { name: "gallery", title: "Gallery Page" },
    { name: "contact", title: "Contact Page" },
    { name: "partners", title: "Partners Section" },
    { name: "community", title: "Community Section" },
    { name: "challenges", title: "Challenges Page & Nav Settings" },
    { name: "theme", title: "Theme & Brand Colors" },
  ],
  fields: [
    // Theme & Brand Colors
    defineField({
      name: "siteName",
      title: "Site Name",
      type: "string",
      group: "theme",
      initialValue: "Shega Generations",
    }),
    defineField({
      name: "siteTagline",
      title: "Site Tagline / Slogan",
      type: "string",
      group: "theme",
      initialValue: "Nurturing Tech Geniuses & Indigenous Leadership in Ethiopia",
    }),
    defineField({
      name: "themePreset",
      title: "Color Theme Preset",
      description: "Select a curated color palette preset, or choose 'Custom Colors' to define custom hex codes below.",
      type: "string",
      group: "theme",
      initialValue: "orange-navy",
      options: {
        list: [
          { title: "Orange & Deep Navy (Default)", value: "orange-navy" },
          { title: "Warm Terracotta & Dark Slate", value: "terracotta-slate" },
          { title: "Deep Emerald & Royal Navy", value: "emerald-navy" },
          { title: "Manuscript Indigo & Sunset Gold", value: "indigo-gold" },
          { title: "Custom Colors (Set below)", value: "custom" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "primaryColor",
      title: "Primary Color (Hex)",
      type: "string",
      group: "theme",
      description: "Main brand color (e.g. #D97706 or #EA580C)",
    }),
    defineField({
      name: "secondaryColor",
      title: "Secondary Color (Hex)",
      type: "string",
      group: "theme",
      description: "Secondary brand color (e.g. #0F172A or #0A192F)",
    }),
    defineField({
      name: "accentColor",
      title: "Accent Color (Hex)",
      type: "string",
      group: "theme",
    }),
    defineField({
      name: "colorPreset",
      title: "Color Preset Identifier",
      type: "string",
      group: "theme",
    }),
    defineField({
      name: "customPrimaryColor",
      title: "Custom Main / Accent Color (Hex)",
      description: "e.g. #EA580C - Used for main buttons, highlights, brand logo mark",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customPrimaryLightColor",
      title: "Custom Light Accent Color (Hex)",
      description: "e.g. #F97316 - Used for active rings, hover states",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customPrimaryDarkColor",
      title: "Custom Dark Accent Color (Hex)",
      description: "e.g. #C2410C - Used for button hover states",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customSecondaryColor",
      title: "Custom Secondary / Navy Color (Hex)",
      description: "e.g. #0A192F - Used for secondary logo text, deep contrast elements",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customSecondaryLightColor",
      title: "Custom Secondary Light Color (Hex)",
      description: "e.g. #1E293B",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customBgColor",
      title: "Custom Page Background Color (Hex)",
      description: "e.g. #F4F3EE",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),
    defineField({
      name: "customTextColor",
      title: "Custom Text Color (Hex)",
      description: "e.g. #1C1E1B",
      type: "string",
      group: "theme",
      hidden: ({ parent }) => parent?.themePreset !== "custom",
    }),

    // Hero Section
    defineField({
      name: "heroTitle",
      title: "Hero Title (Typewriter)",
      type: "string",
      initialValue: "Shega Generations",
      group: "hero",
    }),
    defineField({
      name: "heroCaption",
      title: "Hero Caption",
      type: "text",
      rows: 3,
      initialValue: "Free high-tier software engineering, AI, indigenous Ethiopian history, and character training for talented youth.",
      group: "hero",
    }),
    defineField({
      name: "heroCtaPrimary",
      title: "Hero Primary CTA Text",
      type: "string",
      initialValue: "Join the Generation",
      group: "hero",
    }),
    defineField({
      name: "heroCtaSecondary",
      title: "Hero Secondary CTA Text",
      type: "string",
      initialValue: "Support the Mission",
      group: "hero",
    }),
    defineField({
      name: "heroTitleBgImage",
      title: "Hero Title Mask Background Image",
      description: "Upload custom image asset to fill/mask the typewriter title background",
      type: "image",
      options: { hotspot: true },
      group: "hero",
    }),

    // Statement Banner Section
    defineField({
      name: "statementBannerTitle1",
      title: "Banner Line 1",
      type: "string",
      initialValue: "NURTURING TECH GENIUSES",
      group: "statement",
    }),
    defineField({
      name: "statementBannerTitle2",
      title: "Banner Line 2 (Outlined Stroke)",
      type: "string",
      initialValue: "FOR ETHIOPIA & AFRICA",
      group: "statement",
    }),
    defineField({
      name: "statementBannerTitle3",
      title: "Banner Line 3",
      type: "string",
      initialValue: "FREE COHORT TRAINING & MENTORSHIP",
      group: "statement",
    }),
    defineField({
      name: "statementBannerImage",
      title: "Banner Background Image",
      type: "image",
      options: { hotspot: true },
      group: "statement",
    }),

    // Cultural Anchoring Section
    defineField({
      name: "culturalAnchoringSubtitle",
      title: "Cultural Anchoring Subtitle",
      type: "string",
      initialValue: "Rooted in Indigenous Excellence",
      group: "cultural",
    }),
    defineField({
      name: "culturalAnchoringDescription",
      title: "Cultural Anchoring Description",
      type: "text",
      rows: 3,
      initialValue: "We combine modern computer science with Ge'ez linguistic logic, Ethiopian history, and hospitality character development.",
      group: "cultural",
    }),
    defineField({
      name: "culturalAnchoringImage",
      title: "Cultural Anchoring Background Image",
      type: "image",
      options: { hotspot: true },
      group: "cultural",
    }),

    // Pedagogical Section
    defineField({
      name: "pedagogicalTitle",
      title: "Pedagogical Section Title",
      type: "string",
      initialValue: "Peer Mentorship & Hands-On Engineering",
      group: "pedagogical",
    }),
    defineField({
      name: "pedagogicalDescription",
      title: "Pedagogical Section Description",
      type: "text",
      rows: 3,
      initialValue: "Students learn full-stack development, AI model integration, hardware tinkering, and project management in real commercial client software labs.",
      group: "pedagogical",
    }),

    // Curriculum Section
    defineField({
      name: "curriculumTitle",
      title: "Curriculum Section Title",
      type: "string",
      initialValue: "Complete Engineering & Leadership Curriculum",
      group: "curriculum",
    }),
    defineField({
      name: "curriculumDescription",
      title: "Curriculum Section Description",
      type: "text",
      rows: 3,
      initialValue: "From foundational computer science and web dev to advanced artificial intelligence and indigenous ethics.",
      group: "curriculum",
    }),

    // Journeys Section
    defineField({
      name: "journeysKicker",
      title: "Media Coverage & Projects Section Kicker Tag",
      type: "string",
      initialValue: "Student Media Coverage & Achievements",
      group: "journeys",
    }),
    defineField({
      name: "journeysTitle",
      title: "Media Coverage Section Title",
      type: "string",
      initialValue: "Student Interviews & Media Features",
      group: "journeys",
    }),
    defineField({
      name: "journeysDescription",
      title: "Media Coverage Section Description",
      type: "text",
      rows: 3,
      initialValue: "Radio interviews, podcast features, Facebook broadcasts, and software projects executed by Shega Generation students.",
      group: "journeys",
    }),
    defineField({
      name: "journeysCategories",
      title: "Media Filter Categories",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["Podcasts", "Radio Programs", "Programs", "Interviews"],
      description: "Custom categories for media section filter pills (e.g. Podcasts, Radio Programs, Programs, Interviews)",
      group: "journeys",
    }),

    // Testimonials Section
    defineField({
      name: "testimonialsTitle",
      title: "Testimonials Section Title",
      type: "string",
      initialValue: "Voices of the Generation",
      group: "testimonials",
    }),
    defineField({
      name: "testimonialsDescription",
      title: "Testimonials Section Description",
      type: "text",
      rows: 3,
      initialValue: "Hear from our students, alumni, and community mentors about their transformational journey at Shega Generations.",
      group: "testimonials",
    }),

    // Nearest Gathering / Events Directory Section
    defineField({
      name: "eventsSectionKicker",
      title: "Nearest Gathering Section Kicker Tag",
      type: "string",
      initialValue: "The nearest gathering",
      group: "events",
    }),
    defineField({
      name: "eventsSectionTitle",
      title: "Nearest Gathering Section Title",
      type: "string",
      initialValue: "Upcoming Gathering & Workshops",
      group: "events",
    }),
    defineField({
      name: "eventsPageTitlePhrases",
      title: "Events Page Typewriter Title Phrases",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["Where the generation gathers.", "የትውልዱ መገናኛ"],
      group: "events",
    }),
    defineField({
      name: "eventsPageSubtitle",
      title: "Events Page Subtitle Description",
      type: "text",
      rows: 2,
      initialValue: "Active, incoming and historic meetups from CTFs in Addis to Simien treks.",
      group: "events",
    }),
    defineField({
      name: "eventsCategories",
      title: "Events Filter Categories",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["CTF", "Hackathon", "Hiking", "Tour", "Tech Training", "Charity"],
      group: "events",
    }),

    // Gallery Page Settings
    defineField({
      name: "galleryPageTitlePhrases",
      title: "Gallery Page Typewriter Title Phrases",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["The weave, in pictures.", "በስዕሎች የተሸመነው"],
      group: "gallery",
    }),
    defineField({
      name: "galleryPageSubtitle",
      title: "Gallery Page Subtitle Description",
      type: "text",
      rows: 2,
      initialValue: "Expeditions, hackathons, classrooms, and volunteer work across Ethiopia.",
      group: "gallery",
    }),
    defineField({
      name: "galleryCategories",
      title: "Gallery Filter Categories",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["Expeditions", "Hackathons", "Classroom", "Volunteer-Work"],
      group: "gallery",
    }),

    // Contact Page Settings
    defineField({
      name: "contactPageTitlePhrases",
      title: "Contact Page Typewriter Title Phrases",
      type: "array",
      of: [{ type: "string" }],
      initialValue: ["Get in touch, with Shega.", "ከሸጋ ጋር, ይገናኙ"],
      group: "contact",
    }),
    defineField({
      name: "contactPageSubtitle",
      title: "Contact Page Subtitle Description",
      type: "text",
      rows: 2,
      initialValue: "Reach out to our leadership team for general inquiries, partnerships, sponsorships, media features, or donations.",
      group: "contact",
    }),

    // Partners Section
    defineField({
      name: "partnersKicker",
      title: "Partners Section Kicker Tag",
      type: "string",
      initialValue: "Our clients / partners",
      group: "partners",
    }),
    defineField({
      name: "partnersHeadline",
      title: "Partners Section Headline",
      type: "string",
      initialValue: "Pleasure to work with",
      group: "partners",
    }),
    defineField({
      name: "partnersDescription",
      title: "Partners Section Description",
      type: "text",
      rows: 3,
      initialValue: "Shega Generation collaborates with Ethiopia's premier educational academies, hospitality centers, media houses, and venue operators across Addis Ababa.",
      group: "partners",
    }),

    // Community Section
    defineField({
      name: "communityKicker",
      title: "Community Section Kicker Tag",
      type: "string",
      initialValue: "Community",
      group: "community",
    }),
    defineField({
      name: "communityTitle",
      title: "Community Section Title",
      type: "string",
      initialValue: "Follow the day to day",
      group: "community",
    }),
    defineField({
      name: "communityDescription",
      title: "Community Section Description",
      type: "text",
      rows: 2,
      initialValue: "Stay connected with our daily student builds, summer camp moments, and community updates.",
      group: "community",
    }),
    defineField({
      name: "socialFacebookHandle",
      title: "Facebook Handle / Name",
      type: "string",
      initialValue: "Shega Community Group",
      group: "community",
    }),
    defineField({
      name: "socialFacebookUrl",
      title: "Facebook Link URL",
      type: "url",
      initialValue: "https://web.facebook.com/share/g/18foDKzcBS/",
      group: "community",
    }),
    defineField({
      name: "socialTelegramHandle",
      title: "Telegram Handle / Link",
      type: "string",
      initialValue: "t.me/shegagenerations",
      group: "community",
    }),
    defineField({
      name: "socialTelegramUrl",
      title: "Telegram Link URL",
      type: "url",
      initialValue: "https://t.me/shegagenerations",
      group: "community",
    }),
    defineField({
      name: "socialTikTokHandle",
      title: "TikTok Handle / Link",
      type: "string",
      initialValue: "@samuelgeremew_21",
      group: "community",
    }),
    defineField({
      name: "socialTikTokUrl",
      title: "TikTok Link URL",
      type: "url",
      initialValue: "https://www.tiktok.com/@samuelgeremew_21",
      group: "community",
    }),

    // About Us Page Copy & Hero
    defineField({
      name: "aboutHeroKicker",
      title: "About Hero Kicker / Badge Notice",
      type: "string",
      initialValue: "OUR MISSION & ORIGIN STORY",
      group: "about",
    }),
    defineField({
      name: "aboutPageTitlePhrases",
      title: "About Page Title Phrases (Typewriter)",
      type: "array",
      of: [{ type: "string" }],
      initialValue: [
        "እኛ ማን ነን",
        "ABOUT SHEGA GENERATIONS",
        "OUR ORIGIN STORY",
        "OUR MISSION & VISION",
      ],
      group: "about",
    }),
    defineField({
      name: "aboutPageSubtitle",
      title: "About Page Subtitle / Mission Statement",
      type: "text",
      rows: 3,
      initialValue: "Shega Generations (ሸጋ ትውልድ) is a pioneering non-profit educational movement dedicated to providing free, high-tier software engineering, AI technology, indigenous Ethiopian history, and hospitality character training to talented youth across Ethiopia.",
      group: "about",
    }),
    defineField({
      name: "aboutHeroStats",
      title: "About Hero Key Impact Statistics",
      type: "array",
      group: "about",
      of: [
        defineArrayMember({
          type: "object",
          name: "heroStatItem",
          title: "Impact Stat Box",
          fields: [
            defineField({ name: "value", title: "Stat Value (e.g. 500+)", type: "string" }),
            defineField({ name: "label", title: "Stat Label (e.g. Talented Geniuses Trained)", type: "string" }),
          ],
          preview: {
            select: { title: "value", subtitle: "label" },
          },
        }),
      ],
      initialValue: [
        { _key: "stat_box_1", value: "500+", label: "Talented Geniuses Trained" },
        { _key: "stat_box_2", value: "100% Free", label: "Tuition Cost to Students" },
        { _key: "stat_box_3", value: "12+", label: "Summer & Annual Cohorts" },
        { _key: "stat_box_4", value: "15+", label: "Institutional Partners" },
      ],
    }),

    // Holistic Education Pillars
    defineField({
      name: "aboutPillarsTitle",
      title: "Holistic Education Section Title",
      type: "string",
      initialValue: "Our 4 Pillars of Holistic Education",
      group: "about",
    }),
    defineField({
      name: "aboutPillarsSubtitle",
      title: "Holistic Education Section Subtitle",
      type: "text",
      rows: 2,
      initialValue: "Combining elite computational software engineering with indigenous Ethiopian heritage, dining etiquette, and youth peer mentorship.",
      group: "about",
    }),
    defineField({
      name: "aboutPillarsList",
      title: "Educational Pillars Breakdown",
      type: "array",
      group: "about",
      of: [
        {
          type: "object",
          fields: [
            { name: "title", title: "Pillar Title (English)", type: "string" },
            { name: "titleAmharic", title: "Pillar Title (Amharic)", type: "string" },
            { name: "description", title: "Description", type: "text", rows: 3 },
            { name: "tags", title: "Tags / Key Highlights", type: "array", of: [{ type: "string" }] },
          ],
        },
      ],
    }),
    defineField({
      name: "aboutCampusVisionTitle",
      title: "Shega Innovation Campus Vision Title",
      type: "string",
      initialValue: "Building the Permanent Shega Innovation Campus",
      group: "about",
    }),
    defineField({
      name: "aboutCampusVisionText",
      title: "Shega Innovation Campus Vision Text",
      type: "text",
      rows: 4,
      initialValue: "Our ultimate goal is building our own dedicated 24/7 innovation campus in Addis Ababa—equipped with overnight coding laboratories, hardware workshops, incubation spaces, rest facilities, and multi-tier cohort capacity reachable from every corner of Ethiopia.",
      group: "about",
    }),

    // Organization Structure Settings
    defineField({
      name: "orgStructureTitle",
      title: "Org Structure Section Title",
      type: "string",
      initialValue: "Role & Responsibilities Breakdown",
      group: "about",
    }),
    defineField({
      name: "orgStructureSubtitle",
      title: "Org Structure Section Subtitle",
      type: "string",
      initialValue: "Draft organizational breakdown & governance framework for Shega Generation.",
      group: "about",
    }),

    // Challenges Page & Nav Settings
    defineField({
      name: "showChallengesNav",
      title: "Show 'Challenges' in Navbar",
      description: "Toggle to show or hide the Challenges link in the main navigation bar.",
      type: "boolean",
      initialValue: true,
      group: "challenges",
    }),
    defineField({
      name: "challengesNavLabel",
      title: "Challenges Navbar Link Label",
      type: "string",
      initialValue: "Challenges",
      group: "challenges",
    }),
    defineField({
      name: "challengesHeroTitle",
      title: "Challenges Hero Title",
      type: "string",
      initialValue: "Shega Tech Challenges & Arena",
      group: "challenges",
    }),
    defineField({
      name: "challengesHeroSubtitle",
      title: "Challenges Hero Subtitle",
      type: "string",
      initialValue: "Test your coding speed, logical problem-solving, and algorithmic mastery. Rise to the top of the Shega Leaderboard!",
      group: "challenges",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Global Site Settings & Page Copy" };
    },
  },
});
