import { defineField, defineType } from "sanity";
import { UserIcon } from "@sanity/icons";

export default defineType({
  name: "teamMember",
  title: "Team Members & Leadership",
  type: "document",
  icon: UserIcon,
  fields: [
    defineField({
      name: "englishName",
      title: "English Name",
      type: "string",
      description: "e.g. Samuel Geremew or Sahret Sefa",
    }),
    defineField({
      name: "amharicName",
      title: "Amharic Name (አማርኛ ስም)",
      type: "string",
      description: "e.g. ሳሙኤል ገረመው or ወ/ሮ ሳህረት ሰፋ",
    }),
    defineField({
      name: "name",
      title: "Full Combined Name (Display Name)",
      type: "string",
      description: "e.g. Samuel Geremew (ሳሙኤል ገረመው). Combined auto-display name.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "role",
      title: "Role / Title",
      type: "string",
      description: "e.g. Board Council President, Founder & Executive Director, Public Relations (PR)",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "departments",
      title: "Departments & Governance Categories (Select Multiple Checkboxes)",
      type: "array",
      of: [{ type: "string" }],
      description: "Check all governance categories & departments that apply to this member.",
      options: {
        list: [
          { title: "1. Board of Directors / Council Governance", value: "board" },
          { title: "2. Executive & Operational Leadership", value: "executive" },
          { title: "3. Technical Instructors & AI Mentors", value: "tech" },
          { title: "4. Cultural & Character Advisors", value: "cultural" },
          { title: "5. Student Council & Peer Mentors", value: "student-mentors" },
          { title: "6. Operational Logistics & Field Operations", value: "operations" },
          { title: "7. Media, PR & Communications", value: "media" },
          { title: "8. External Advisory Board", value: "advisory" },
        ],
      },
    }),
    defineField({
      name: "isBoardMember",
      title: "Is Board Member? (Switch)",
      type: "boolean",
      initialValue: false,
      description: "Toggle ON if this member serves on the Board of Directors.",
    }),
    defineField({
      name: "isExecutiveLeader",
      title: "Is Executive Leader? (Switch)",
      type: "boolean",
      initialValue: false,
      description: "Toggle ON if this member belongs to Executive & Operational Leadership.",
    }),
    defineField({
      name: "isTeacher",
      title: "Is Teacher / Instructor? (Switch)",
      type: "boolean",
      initialValue: false,
      description: "Toggle ON if this member is a Teacher, Technical Instructor, or Mentor.",
    }),
    defineField({
      name: "teachingSubject",
      title: "Teaching Subject / Specialization",
      type: "string",
      description: "e.g. Python Programming, AI Command Engineering, Ge'ez Linguistics, Full-Stack Web Dev",
    }),
    defineField({
      name: "teachingPeriod",
      title: "Teaching Period / Tenure",
      type: "string",
      description: "e.g. 2021 – Present or Summer 2023 – 2025",
    }),
    defineField({
      name: "isFeatured",
      title: "Featured Showcase (Switch)",
      type: "boolean",
      initialValue: true,
      description: "Toggle ON to feature this member profile prominently across directories.",
    }),
    defineField({
      name: "responsibilities",
      title: "Core Responsibilities & Breakdown",
      type: "text",
      rows: 3,
      description: "Specific duties & role breakdown (e.g. Provides strategic vision, high-level governance, and institutional oversight...)",
    }),
    defineField({
      name: "bio",
      title: "Biography / Background",
      type: "text",
      rows: 4,
    }),
    defineField({
      name: "quote",
      title: "Personal Motto / Quote",
      type: "string",
    }),
    defineField({
      name: "avatar",
      title: "Profile Photo",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "organizationAffiliations",
      title: "Organization Affiliations / Background Tags",
      type: "array",
      of: [{ type: "string" }],
      description: "e.g. Board Council President, Higher Ed Lecturer, Chief Coordinator",
    }),
    defineField({
      name: "socialLinks",
      title: "Social Media & Profile Links",
      type: "object",
      fields: [
        { name: "linkedin", title: "LinkedIn URL", type: "url" },
        { name: "facebook", title: "Facebook URL", type: "url" },
        { name: "tiktok", title: "TikTok URL", type: "url" },
        { name: "email", title: "Email Address", type: "string" },
      ],
    }),
    defineField({
      name: "order",
      title: "Display Order",
      type: "number",
      initialValue: 1,
    }),
  ],
});
